### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by evzhy** [ArcanumSoftworks/Arcanum-Engine#2]
Hello, this isn't really an issue, I'm just about to start working on the same opensource implementation for Arcanum and wondering, what's the state of this project? What does work, what doesn't, where did the development stop, what's there to be done, will the author(s) continue working on it?

Arcanum clearly lacks:
1. support of modern hardware (optimus, 4K, mobile)
2. unrestricted UI (more than 2 components for crafting recipes, more than 5 spells per magic school)
3. control over actions and leveling of companions

I also thought about action-based fight system instead of turn-based, but that's extra.

**Comment by pkurras** [comment]
Hello @evzhy, your assumption isn't quite right, unfortunately. The engine wasn't supposed to be a reimplementation of `Arcanum: Of Steamworks and Magick Obscura` if that's what you're referring to. They just share a name. Progress has also been very slow since I worked on it in my spare time - which is very constrained. All that's left to say is - have fun with your engine approach then. :)
